# Generated by Django 5.2.3 on 2026-06-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
